; PlatformIO Project Configuration File
; Acoustic ATCS Proxy Node
; ESP32 + INMP441 I2S Microphone + MQTT

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 921600
build_flags =
    -D CORE_DEBUG_LEVEL=1
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0
